const constants = {
	AppURL: 'http://localhost:3000',
	FacebookURL: 'https://graph.facebook.com/v2.11',
	LOGIN_FACEBOOK_REQUEST: 'LOGIN_FACEBOOK_REQUEST',
	LOGIN_FACEBOOK_SUCCESS: 'LOGIN_FACEBOOK_SUCCESS',
	LOGIN_FACEBOOK_FAILURE: 'LOGIN_FACEBOOK_FAILURE',
	GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
	GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
	GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
	SET_CURRENT_REVIEW: 'SET_CURRENT_REVIEW',
	SET_SELECTED_USER: 'SET_SELECTED_USER',
	CHANGE_USER_DESCRIPTION_REQUEST: 'CHANGE_USER_DESCRIPTION_REQUEST',
	CHANGE_USER_DESCRIPTION_SUCCESS: 'CHANGE_USER_DESCRIPTION_SUCCESS',
	CHANGE_USER_DESCRIPTION_FAILURE: 'CHANGE_USER_DESCRIPTION_FAILURE'
}

export default constants