const constants = {
	AppURL: 'http://localhost:3000',
	FacebookURL: 'https://graph.facebook.com/v2.11',
	GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
	GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
	GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
	SET_CURRENT_REVIEW: 'SET_CURRENT_REVIEW',
	SET_SELECTED_USER: 'SET_SELECTED_USER'
}

export default constants